sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t jccomputing/rpi-domoticz .
# test image
- docker run --entrypoint /src/domoticz/domoticz jccomputing/rpi-domoticz
# push image
- >-
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push jccomputing/rpi-domoticz
  fi
